In [2]:
import numpy as np
print(np.__version__)

2.1.3


In [10]:
a = [10,20,30.1]
print(a)
type(a)

b=np.array(a)
print(b)

[10, 20, 30.1]
[10.  20.  30.1]


In [11]:
b+100

array([110. , 120. , 130.1])

In [12]:
np.shape(b)

(3,)

In [13]:
b.dtype

dtype('float64')

In [14]:
c=np.array([1,2,3], dtype=complex)
print(c)
print(c.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128


In [16]:
d=np.array([[1,2,3],[4,5,6]])
print(d)
print(d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
