In [2]:
import numpy as np
arr = np.array([1, 3, 5, 7, 9])
print(np.mean(arr), np.median(arr), np.std(arr), np.var(arr), np.ptp(arr))

5.0 5.0 2.8284271247461903 8.0 8


In [5]:
print(np.amin(arr))

1


In [6]:
print(np.amax(arr))

9


In [7]:
np.percentile(arr, 50)

np.float64(5.0)

In [8]:
# Random

rng = np.random.default_rng()  # Modern RNG (recommended)

print(rng.random(3))           # 1D array: [0.548, 0.715, 0.602] (varies)
print(rng.random((2, 3)))      # 2D: [[0.424, 0.658, 0.118], [0.908, 0.207, 0.232]]
print(rng.uniform(-1, 1, 5))   # Range -1 to 1: [-0.301, 0.956, -0.601, 0.418, 0.023]

[0.12176557 0.98662767 0.57268119]
[[0.93904107 0.08578913 0.07306964]
 [0.36197126 0.27220949 0.47871542]]
[-0.44004449  0.49414824  0.1840222   0.53398261 -0.15829085]


In [9]:
print(rng.integers(0, 10, 4))  # 0-9: [7, 4, 2, 9]
print(rng.integers(1, 7, (2,3)))  # Dice rolls: [[3, 6, 2], [4, 1, 5]]

[8 2 7 9]
[[3 4 2]
 [1 6 2]]


In [10]:
fruits = np.array(['apple', 'banana', 'cherry'])
print(rng.choice(fruits, 3))         # With replacement: ['banana', 'apple', 'cherry']
print(rng.choice(fruits, 2, replace=False))  # Without: ['cherry', 'apple']

['banana' 'apple' 'cherry']
['cherry' 'banana']


In [13]:
arr = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr)         # In-place: [3, 1, 5, 2, 4]
print(rng.permutation([10, 20, 30]))  # New shuffled copy: [30, 10, 20]

[20 10 30]


In [14]:
# Matlib
import numpy as np
import numpy.matlib as matlib

In [15]:
print(matlib.eye(3))
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
print(matlib.zeros((2,3)))
# [[0. 0. 0.]
#  [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]
