In [1]:
import numpy as np

# Create array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Vectorized operations (much faster than loops)
print("Squared:", arr ** 2)
print("Mean:", np.mean(arr))
print("Random 3x3 matrix:\n", np.random.rand(3, 3))

# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Matrix product:\n", np.dot(a, b))

Array: [1 2 3 4 5]
Squared: [ 1  4  9 16 25]
Mean: 3.0
Random 3x3 matrix:
 [[0.69210499 0.15634743 0.98619254]
 [0.82451856 0.2508549  0.84136521]
 [0.4706763  0.6931213  0.71042299]]
Matrix product:
 [[19 22]
 [43 50]]


In [19]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# Easy filtering and grouping
print("Salary > 55k:\n", df[df['Salary'] > 55000])
print("Average age:", df['Age'].mean())

# Group by (simulates SQL)
df['AgeGroup'] = pd.cut(df['Age'], bins=2)
print("\nGrouped by age:\n", df.groupby('AgeGroup', observed=False)['Salary'].mean(),)

DataFrame:
       Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
Salary > 55k:
       Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   70000
Average age: 30.0

Grouped by age:
 AgeGroup
(24.99, 30.0]    55000.0
(30.0, 35.0]     70000.0
Name: Salary, dtype: float64


In [20]:
print(np.__version__)

2.3.4
