In [8]:
import numpy as np

In [9]:
arr=np.array([[1,2,3,4], [5,6,7,8]])
print(arr, type(arr))

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [10]:
print(arr.ndim) # dimension

2


In [11]:
print(arr.shape)

(2, 4)


In [12]:
print(arr.dtype)

int64


In [14]:
print(arr[1][0])

5


In [15]:
print(arr[1, 0]) # Only in NumPy, in Python error

5


In [18]:
arr = np.array([1,2,3,4,5])
arr[1:3]

array([2, 3])

In [20]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [21]:
for x in np.nditer(arr):
    print(x)

1
2
3


In [22]:
arr = np.array([[1,2,3],[4,5,6]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
np.full((2,2,2),99, dtype="int32")

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]], dtype=int32)

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])