In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
print(a1.shape, a2.shape, a3.shape)

(3,) (2, 3) (2, 3, 3)


In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int64')

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [17]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 6, 5, 2, 9],
       [5, 9, 0, 9, 6],
       [3, 8, 0, 7, 7]])

In [20]:
random_array.size, random_array.shape

(15, (3, 5))

In [21]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.77397304, 0.47208277, 0.25049057],
       [0.98471064, 0.8880822 , 0.22475202],
       [0.56096402, 0.17814053, 0.45536069],
       [0.44352372, 0.35908083, 0.20167416],
       [0.53406398, 0.20759597, 0.74593806]])

In [22]:
random_array_2.shape

(5, 3)

In [23]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [24]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [27]:
random_array2 = np.random.randint(0, 10, size=(2,3, 5))
random_array2

array([[[6, 1, 5, 1, 6],
        [9, 8, 6, 5, 9],
        [7, 5, 4, 9, 6]],

       [[8, 1, 5, 5, 8],
        [3, 7, 7, 9, 4],
        [7, 5, 9, 6, 2]]])

In [29]:
random_array3 = np.random.randint(0, 10, size=(2,2,3, 5))
random_array3

array([[[[9, 3, 4, 0, 3],
         [5, 6, 4, 0, 4],
         [1, 5, 2, 4, 8]],

        [[7, 5, 7, 5, 3],
         [7, 6, 2, 3, 1],
         [1, 8, 4, 2, 1]]],


       [[[7, 0, 8, 8, 1],
         [2, 3, 0, 1, 1],
         [5, 5, 6, 0, 9]],

        [[3, 2, 4, 2, 8],
         [4, 9, 0, 0, 2],
         [6, 3, 9, 5, 4]]]])