In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
print(a1.shape, a2.shape, a3.shape)

(3,) (2, 3) (2, 3, 3)


In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int64')

In [16]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [18]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 9, 2, 1, 1],
       [3, 3, 6, 2, 2],
       [1, 6, 6, 6, 5]])

In [21]:
random_array.size, random_array.shape

(15, (3, 5))

In [22]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.50261141, 0.75132334, 0.26796277],
       [0.82358638, 0.89659581, 0.66871626],
       [0.91592527, 0.20631194, 0.92291656],
       [0.04764172, 0.62930009, 0.74428927],
       [0.48010676, 0.30416581, 0.71137644]])

In [23]:
random_array_2.shape

(5, 3)

In [24]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [25]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [26]:
random_array2 = np.random.randint(0, 10, size=(2,3, 5))
random_array2

array([[[3, 5, 8, 8, 7],
        [5, 0, 0, 2, 8],
        [9, 6, 4, 9, 7]],

       [[3, 3, 8, 3, 0],
        [1, 0, 0, 6, 7],
        [7, 9, 3, 0, 7]]])

In [27]:
random_array3 = np.random.randint(0, 10, size=(2,2,3, 5))
random_array3

array([[[[7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5]],

        [[9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1]]]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [29]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [30]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [31]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## Viewing arrays and matrices

In [32]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [34]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [35]:
a1[0]

np.int64(1)

In [36]:
a2.shape, a2[0]

((2, 3), array([1. , 2. , 3.3]))

In [37]:
a3.shape, a3[0]

((2, 3, 3),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [38]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [39]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [40]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [43]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## Manipulating & comparing arrays

### Arithmetic

In [44]:
a1

array([1, 2, 3])

In [45]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [46]:
a1+ones

array([2., 3., 4.])

In [47]:
a1-ones

array([0., 1., 2.])

In [48]:
a1*ones

array([1., 2., 3.])

In [49]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [50]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [54]:
a1/ones # Elemement-wise!

array([1., 2., 3.])

In [55]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [56]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [57]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [58]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [59]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [60]:
np.add(a1, ones)

array([2., 3., 4.])

In [61]:
a1 % 2

array([1, 0, 1])

In [62]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [63]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [64]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])